### ISSUE TITLE
errors just errors

### ISSUE THREAD

**Issue by surjit** [hsoft/pdfmasher#28]
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.

root@pdf-html:/home/surjit/public_html/pdfmasher# python build.py
Traceback (most recent call last):
  File "build.py", line 18, in <module>
    from hscommon import sphinxgen
  File "/home/surjit/public_html/pdfmasher/hscommon/sphinxgen.py", line 14, in <module>
    from .build import read_changelog_file, filereplace
  File "/home/surjit/public_html/pdfmasher/hscommon/build.py", line 317
    def copy_resources(self, *resources, use_symlinks=False):
                                                    ^
SyntaxError: invalid syntax

**Comment by hsoft** [comment]
That's because you run the app with Python 2. PdfMasher is a Python 3 program.

**Comment by surjit** [comment]
thanks, i will run  it on python 3
